declare const process: any;
import { cards, chooseIntervention, drawAfterBattle, scoreRound } from '../src/engine/game';
import { beatsCard, canBeatSet, hasIntervention } from '../src/rules/cards';
import { respond, resolveBattle, specialPenaltyTarget, startBattle } from '../src/rules/battle';
import { createPlayers } from '../src/model/cards';
const trump={noTrump:false as const,trumpSuit:'hearts' as const}; const nt={noTrump:true as const};
const assert = { equal:(a:any,b:any)=>{ if(a!==b) throw new Error(`${a} !== ${b}`); }, deepEqual:(a:any,b:any)=>{ if(JSON.stringify(a)!==JSON.stringify(b)) throw new Error(`${JSON.stringify(a)} !== ${JSON.stringify(b)}`); }, throws:(f:()=>void)=>{ let ok=false; try{f();}catch{ok=true;} if(!ok) throw new Error('Expected throw'); } };
const tests: [string,()=>void][]=[]; const it=(n:string,f:()=>void)=>tests.push([n,f]);
it('compares ordinary cards',()=>assert.equal(beatsCard(cards('KS')[0],cards('AS')[0],trump),true));
it('trump beats non-trump',()=>assert.equal(beatsCard(cards('AS')[0],cards('6H')[0],trump),true));
it('no-trump mode has no trump',()=>assert.equal(beatsCard(cards('AS')[0],cards('6H')[0],nt),false));
it('Shaman is unbeatable',()=>assert.equal(beatsCard(cards('6S')[0],cards('AH')[0],trump),false));
it('Shaman substitutes suit',()=>assert.equal(hasIntervention(cards('10H JH QH 6S'),trump),true));
it('rejects partial beating',()=>assert.equal(canBeatSet(cards('AS 10S'),cards('KS QS'),trump),false));
it('allows voluntary discard',()=>{let b=startBattle(0 as any,cards('7C'),trump); b=respond(b,1 as any,cards('AC'),'discard',trump); assert.equal(b.sets[1].kind,'discard');});
it('bank goes to last beating player',()=>{let b=startBattle(0 as any,cards('7C'),trump); b=respond(b,1 as any,cards('8C'),'open',trump); b=respond(b,2 as any,cards('9C'),'open',trump); b=respond(b,3 as any,cards('6D'),'discard',trump); assert.equal(resolveBattle(b).bankOwnerId,2);});
it('battle ends after 4 actions',()=>{let b=startBattle(0 as any,cards('7C'),trump); b=respond(b,1 as any,cards('8C'),'open',trump); b=respond(b,2 as any,cards('9C'),'open',trump); b=respond(b,3 as any,cards('6D'),'discard',trump); assert.throws(()=>respond(b,0 as any,cards('AC'),'open',trump));});
it('draw starts from bank owner clockwise',()=>{const ps=createPlayers(); ps.forEach(p=>p.hand=[]); const r=drawAfterBattle(ps,cards('AS AH AD AC'),2 as any); assert.deepEqual(r.players.map(p=>p.hand.map(c=>c.rank+c.suit[0])),[['Ad'],['Ac'],['As'],['Ah']]);});
it('intervention priorities',()=>{assert.equal(chooseIntervention([1,2] as any,0 as any),2); assert.equal(chooseIntervention([2,0] as any,1 as any),2);});
it('four aces +12 to opponents if unbeaten',()=>{let b=startBattle(0 as any,cards('AS AH AD AC'),trump,12); b=respond(b,1 as any,cards('7D 8D 9D JD'),'discard',trump); b=respond(b,2 as any,cards('7H 8H 9H JH'),'discard',trump); b=respond(b,3 as any,cards('7C 8C 9C JC'),'discard',trump); assert.equal(specialPenaltyTarget(resolveBattle(b)),'B');});
it('four aces reflect when beaten',()=>{let b=startBattle(0 as any,cards('AS AH AD AC'),trump,12); b=respond(b,1 as any,cards('6S 10H KH QH'),'open',trump); b=respond(b,2 as any,cards('7D 8D 9D JD'),'discard',trump); b=respond(b,3 as any,cards('7C 8C 9C JC'),'discard',trump); assert.equal(specialPenaltyTarget(resolveBattle(b)),'A');});
it('four sixes ordinary mode cannot be fully beaten',()=>assert.equal(canBeatSet(cards('6S 6H 6D 6C'),cards('AH 7H 7D 7C'),trump),false));
it('four sixes no-trump can be beaten',()=>assert.equal(canBeatSet(cards('6S 6H 6D 6C'),cards('7S 7H 7D 7C'),nt),true));
it('penalties 0 / 1-30 / 31-59',()=>{assert.equal(scoreRound(0,120).penalties.A,6); assert.equal(scoreRound(30,90).penalties.A,4); assert.equal(scoreRound(59,61).penalties.A,2);});
it('eggs accumulate debt',()=>{let a=scoreRound(60,60,0); let b=scoreRound(60,60,a.eggDebt); assert.equal(scoreRound(20,100,b.eggDebt).penalties.A,8);});
it('taunt after four-card beat',()=>{let b=startBattle(0 as any,cards('6C 7C 8C 9C'),trump); b=respond(b,1 as any,cards('10C JC QC KC'),'open',trump); assert.equal(b.tauntAvailableFor?.includes(1 as any),true);});
let passed=0; for(const [n,f] of tests){ try{f(); console.log('✓',n); passed++;}catch(e){console.error('✗',n); console.error(e); process.exit(1);} } console.log(`${passed} tests passed`);
